blog_system/urls.py
from django.contrib import admin
from django.urls import path,include
from body import urls as body_index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('body/',include(body_index)),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

body/urls.py
from django.urls import path,include
from body import views

app_name='body'

urlpatterns = [
    path('index/', views.index, name='index'), # 首页
    path('dynamic_state/', views.dynamic_state, name='dynamic_state'), # 动态
    path('music/', views.music, name='music'), # 音乐
    # path('photo_album/', views.photo_album, name='photo_album'), # 相册
    path('personal/', views.personal, name='personal'), # 个人档
    path('chat/', views.chat, name='chat'), # 聊天系统
    path('publish/', views.publish1.as_view(), name='publish'),
    path('Love_article/', views.Love_article2, name='Love_article2'),
    path('move_text1/', views.move_text1, name='move_text1'),
    path('comment/', views.Commnets, name='Comment'),
    path('thumps_up2', views.thumps_up2, name='thumps_up2'),
    path('indexs/<int:us_id>/',views.indexs,name='indexs'),
    path('qiandao/',views.qiandao,name='qiandao'),
    path('guanzhu/',views.guanzhu,name='guanzhu'),
    path('noguanzhu/',views.noguanzhu,name='noguanzhu'),
    path('Comments_2/', views.Comments_2, name='Comments_2'),
    path('publish/', views.publish1.as_view(), name='publish'),
    path('move_text1/', views.move_text1, name='move_text1'),
    path('Love_article2/', views.Love_article2, name='Love_article2'),
    # path('get_page/', views.get_page, name='get_page'),
]

login/urls.py
from login import views
from django.urls import path

app_name='logins'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('',views.login, name='login'),
    path('code/', views.verify_code, name='code'),
    path('forget/',views.forgetpassword,name='forget'),
    path('change/',views.change,name='change'),
    path('zhuce/',views.zhuce,name='zhuce'),
]

templates/account_template.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta content="名榜" http-equiv="keywords">
<meta name="description" content="名榜,wangid">
<meta name="viewport" content="width=device-width,user-scalable=no, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<title>登录</title>
<!-- css -->
<link rel="stylesheet" type="text/css" href="{% static 'login_and_registration/css/index.css' %}">
<link href="{% static 'login_and_registration/css/skitter.styles.css' %}" type="text/css" media="all" rel="stylesheet" />
<!-- js -->
<script type="text/javascript" src="{% static 'login_and_registration/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'login_and_registration/js/public.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'login_and_registration/js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'login_and_registration/js/jquery.skitter.min.js' %}"></script>
<!-- Init Skitter -->
<script type="text/javascript" language="javascript">
	$(document).ready(function() {
		$('.box_skitter_large').skitter({
			theme: 'clean',
			numbers_align: 'center',
			progressbar: false,
			dots: true,
			preview: true,
			stop_over:false,
		});
	});
</script>

</head>

<body>
	<div class="top_box">
		<div class="wid_con">
			<div class="top_con">
				<div class="top_logo">
					<a href="{% url 'body:index' %}">
						<img src="{% static 'login_and_registration/images/logo_touming.gif' %}">
					</a>
					<span>{% block static %}{% endblock %}</span>
				</div>
			</div>
		</div>
	</div>
	<div class="content">
        {% block body %}

        {% endblock %}
	</div>
	<!-- footer -->
	<div class="footer">
		<p>版权所有&nbsp;&nbsp;&nbsp;Copyright © 地表最强小组&nbsp;&nbsp;&nbsp;&nbsp;电话：400-6677-937</p>
		<p><a>京ICP备：14012449号</a>黔ICP证：黔B2-20140009号<span>京公网安备：11010602030054号</span></p>
	</div>
</body>
</html>

templates/change_password.html
{% extends 'account_template.html' %}
{% load staticfiles %}

{% block static %}
    密码修改/Change Password
{% endblock %}

{% block body %}
    <div class="wid_con loginbox">
        <div class="password_con change_password">
            <div class="text_box">
                <div>
                    <div><i><img src="images/icon02.png"></i><input type="text" placeholder="请输入6~30位新密码">
                        <span>*</span>
                    </div>
                    <section class="pass_long">
                        <h1>密码强度：弱&nbsp;&nbsp;&nbsp;中&nbsp;&nbsp;&nbsp;强</h1>
                    </section>
                    <div class="qrmm"><i><img src="images/icon02.png"></i><input type="text" placeholder="请输入密码确认">
                        <span>*</span>
                    </div>
                    <a href="{% url 'logins:login' %}">
                        <button>确认修改</button>
                    </a>
                </div>
            </div>
            <script type="text/javascript">
                $(function () {
                    $(".text_box>div>.qrmm input").focus(
                        function () {
                            $(".text_box .qrmm i img").stop().animate({marginTop: -22}, 100)
                        }
                    )
                })
            </script>
        </div>
        <div class="password_txt">
            <div>
                <h1>温馨提示</h1>
                <p>密码修改后请牢记您的新密码，如有问题请致电服务热线：400-6677-937</p>
            </div>
            <h2>请点此<a href="index.html">登录</a></h2>
        </div>
    </div>
{% endblock %}

templates/chat_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div id="first" style="position: relative;width: 600px;height: 350px;margin: auto;margin-top: 30px">

<div style="width: 600px;height: 345px;z-index: 999;border: 1px dashed #000000;position: absolute;">
    {{ user }} <br> {{ a }}
</div>
    <div style="width: 600px;height: 150px;">
<form action="{% url 'chat:halo' %}" method="post">
    {% csrf_token %}
    <input type="text" name="xinxi" style="width: 600px;height: 150px;position: absolute;margin-top: 346px;border-left: 1px dashed #000000;padding-bottom: 10px;font-size: 20px">

    <input type="submit" value="发送(s)" style="position: absolute;margin-top: 460px;margin-left: 500px">
</form>
        </div>
</div>

</body>
</html>

templates/end_chat.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title></title>

<link rel="stylesheet" type="text/css" href="{% static 'css/qq.css' %}"/>

</head>
<script src="{% static 'js/jquery-1.12.4.min.js ' %}"></script>
<script>
    $(function () {
            $('.intername').click(function () {
                //获取想要的数据

                pwd = $('.IP2').val()
                name1 = $('.PORT2').val()

                $.ajax({
                    'url':'/chat/info/',
                    'type':'post',
                    'data':{"IP":pwd,"PORT":name1},
                    'dataType':'json',
                    'async':false
                }).success(function (data) {
                    $('.newsList').show().html(data.res)
                })
            })
        })



     {#$(function () {#}
     {#       $('.sendBtn').click(function () {#}
     {#           //获取想要的数据#}
     {##}
     {#           xinxi = $('.dope').val()#}
     {##}
     {##}
     {#           $.ajax({#}
     {#               'url':'/chat/info/',#}
     {#               'type':'post',#}
     {#               'data':{"xinxi":xinxi,},#}
     {#               'dataType':'json',#}
     {#               'async':false#}
     {#           }).success(function (data) {#}
     {#               if (data.res == 1){#}
     {#                   alert('接收成功')#}
     {#               }#}
     {#           })#}
     {#       })#}
     {#   })#}
</script>
<body>

<div class="qqBox">
	<div class="BoxHead">
		<div class="headImg">
			<img src="img/6.jpg"/>
		</div>
		<div class="internetName">90后大叔</div>
	</div>
	<div class="context">
		<div class="conLeft">
			<ul>















            {% for i in a %}
                <li>
{#                    此处是每个人的头像#}
					<div class="liLeft"><img src="img/20170926103645_54.jpg"/></div>

					<div class="liRight">
{#                        此处是每个人的名字#}
						<span  class="intername">{{ i.a_b_user.user_name }}</span>

                        <input type="button" value="{{ i.a_b_user.user_IP }}" style="display: none" class="IP2">
                        <input type="button" value="{{ i.a_b_user.user_PORT }}" style="display: none" class="PORT2">

					</div>
				</li>
            {% endfor %}

			</ul>
		</div>
		<div class="conRight">
			<div class="Righthead">
				<div class="headName"></div>
			</div>
			<div class="RightCont">
				<ul class="newsList">
                    {{ abc }}
				</ul>
			</div>
			<div class="RightFoot">
{#                此处写发送的from表单#}
				<div class="inputBox">
                    <form action="{% url 'chat:halo' %}" method="post">
					<input  style="width: 99%;height: 75px; border: none;outline: none;" name="xinxi" >

					<input type="submit" value="发送(s)">
                        </form>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/chat.js' %}"></script>

</body>
</html>

templates/forget_1.html
{% extends 'account_template.html' %}
{% block static %}
    修改密码/Forget
{% endblock %}

{% block body %}
    <p2>请输入您得是手机号</p2>
    <form action="{% url 'logins:change' %}" method="post">
        {% csrf_token %}
        <input type="text" name="yzm" placeholder="请输入验证码">
        <input type="text" name="pwd" pattern="[0-9|A-z]{6}" placeholder="请输入6位密码">
        <input type="submit" value="修改">
    </form>
{% endblock %}

templates/forgetpassword.html
{% extends 'account_template.html' %}
{% block static %}
    修改密码/Forget
{% endblock %}

{% block body %}
    <p2>请输入您得手机号</p2>
    <form action="{% url 'logins:forget' %}" method="post">
        {% csrf_token %}
    <input type="text" name="tel" pattern="^(0|86|17951)?(13[0-9]|15[012356789]|17[0678]|18[0-9]|14[57])[0-9]{8}" minlength="11" maxlength="11" placeholder="请输入11位手机号码" >
    <input type="submit" value="提交">
    </form>
{% endblock %}

templates/log.html
{% extends 'account_template.html' %}
{% load staticfiles %}

{% block static %}
    登录/Login
{% endblock %}

{% block body %}

    <div class="wid_con loginbox">
        <div class="border_box">
            <div class="box_skitter box_skitter_large">
                <ul>
                    <li><img src="{% static 'login_and_registration/images/login_pic01.jpg' %}" class="cube"/></li>
                    <li><img src="{% static 'login_and_registration/images/case_bg.jpg' %}" class="cubeRandom"/></li>
                    <li><img src="{% static 'login_and_registration/images/banner1.jpg' %}" class="cubeStop"/></li>
                </ul>

            </div>
        </div>
        <form action="{% url 'logins:login' %}" method="post">
            {% csrf_token %}
        <div class="login_con">
            <h1>登录/LOGIN</h1>
            <div class="text_box">
                <div>

                    <div><i><img src="images/icon01.png"></i><input  type="tel" name="tel" pattern="^(0|86|17951)?(13[0-9]|15[012356789]|17[0678]|18[0-9]|14[57])[0-9]{8}" minlength="11" maxlength="11" placeholder="请输入11位手机号码" >
                    </div>
                    <div><i><img src="images/icon02.png"></i><input type="password" name="pwd" pattern="[0-9|A-z]{6}" placeholder="请输入6位密码">
                    </div>
                    <div class="yzm">
                        <img id="yzm" src="{% url 'logins:code' %}" style="left: 400px"><input type="text" name="yzm">

                    <h3>
                        <a href="{% url 'logins:forget' %}">忘记密码？</a>
                        <a href="{% url 'logins:register' %}">没有帐号？免费注册！</a>
                    </h3>
                    <input type="submit" value="登陆">
                </div>
            </div>
        </div>
        </div>
    </form>
    </div>

{% endblock %}

templates/parent_template.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'login_and_registration/images/tx.jpg' %}"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>地表最强博客</title>
    <meta name="keywords" content="地表最强博客"/>
    <meta name="description" content="地表最强博客"/>
    <style type="text/css">
        img.wp-smiley,
        img.emoji {
            display: inline !important;
            border: none !important;
            box-shadow: none !important;
            height: 1em !important;
            width: 1em !important;
            margin: 0 .07em !important;
            vertical-align: -0.1em !important;
            background: none !important;
            padding: 0 !important;
        }
    </style>
    <link rel='stylesheet' id='style-css' href='{% static 'home/css/style.css' %}' type='text/css'
          media='all'/>
    <link rel='stylesheet' id='lmlblog-css' href='{% static 'home/css/lmlblog.css' %}' type='text/css'
          media='all'/>
    <link rel='stylesheet' id='all-css' href='{% static 'home/css/all.css' %}' type='text/css'
          media='all'/>
    <link rel="stylesheet" href="{% static 'chat/css/style.css' %}">
    <script type='text/javascript' src='{% static 'home/js/jquery.min.js' %}'></script>
    <script type='text/javascript'>
        {#function ajax_header(id) {#}
        {#    $.ajax({#}
        {#        'url': '{% url 'body:indexs' %}',#}
        {#        'dataType': 'json',#}
        {#        'type': 'get',#}
        {#        'data': {'us_id': id},#}
        {#        'success': (function (data) {#}
        {#            var arr = data;#}
        {#            location.href = "{% url 'body:index' %}";#}
        {#            alert('1');#}
        {#            $('#info_img').attr('src', arr.img).attr('onclick', 'ajax_header(' + arr.user_id + ')');#}
        {#            $('#info_img_name').attr('title', arr.user_name);#}
        {#            $('#info_user_name').html(arr.user_name);#}
        {#            $('#info_grade').html('LV.' + arr.grade).attr('title', arr.signnumber);#}
        {#            $('#info_sgrade').html('LV.' + arr.sgrade);#}
        {#            $('#info_sign').html(arr.user_sign);#}
        {#            if (arr.hh == 1) {#}
        {#                $('#hh').attr('onclick', 'qiandao(' + arr.user_id + ')');#}
        {#                $('#heheda').html('<i class="lmlblog-icon"></i> 签到 </span>')#}
        {#            } else if (arr.hh == 2) {#}
        {#                $('#hh').attr('onclick', '');#}
        {#                $('#heheda').html('<i class="lmlblog-icon"></i> 已签到 </span>')#}
        {#            } else if (arr.hh == 3) {#}
        {#                $('#hh').attr('onclick', 'guanzhu(' + arr.user_id + ')');#}
        {#                $('#heheda').html('<i class="lmlblog-icon"></i> 关注 </span>')#}
        {#            } else if (arr.hh == 4) {#}
        {#                $('#hh').attr('onclick', 'noguanzhu(' + arr.user_id + ')');#}
        {#                $('#heheda').html('<i class="lmlblog-icon"></i> 取消关注 </span>')#}
        {#            }#}
        {#        })#}
        {#    })#}
        {# }#}

        function qiandao(id) {
            if (hh.getAttribute('lock')) {
                return;
            }
            //上锁
            hh.setAttribute('lock', 1);
            $.ajax({
                'url': '{% url "body:qiandao" %}',
                'type': 'post',
                'dataType': 'json',
                'data': {'us_id': id},
                'success': (function (data) {
                    hh.setAttribute('lock', '');
                    var arr = data;
                    if (arr.hh == 1) {
                        $('#hh').attr('onclick', 'qiandao(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 签到 </span>')
                    } else if (arr.hh == 2) {
                        $('#hh').attr('onclick', '');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 已签到 </span>')
                    } else if (arr.hh == 3) {
                        $('#hh').attr('onclick', 'guanzhu(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 关注 </span>')
                    } else if (arr.hh == 4) {
                        $('#hh').attr('onclick', 'noguanzhu(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 取消关注 </span>')
                    }
                })

            })
        }

        function guanzhu(id) {
            if (hh.getAttribute('lock')) {
                return;
            }
            //上锁
            hh.setAttribute('lock', 1);
            $.ajax({
                url: '{% url 'body:guanzhu' %}',
                dataType: 'json',
                type: 'post',
                data: {'us_id': id},
                success: (function (data) {
                    hh.setAttribute('lock', '');
                    var arr = data;
                    if (arr.hh == 1) {
                        $('#hh').attr('onclick', 'qiandao(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 签到 </span>')
                    } else if (arr.hh == 2) {
                        $('#hh').attr('onclick', '');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 已签到 </span>')
                    } else if (arr.hh == 3) {
                        $('#hh').attr('onclick', 'guanzhu(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 关注 </span>')
                    } else if (arr.hh == 4) {
                        $('#hh').attr('onclick', 'noguanzhu(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 取消关注 </span>')
                    }
                })
            })
        }

        function noguanzhu(id) {
            if (hh.getAttribute('lock')) {
                return;
            }
            //上锁
            hh.setAttribute('lock', 1);
            $.ajax({
                url: '{% url 'body:noguanzhu' %}',
                dataType: 'json',
                type: 'post',
                data: {'us_id': id},
                success: (function (data) {
                    hh.setAttribute('lock', '');
                    var arr = data;
                    if (arr.hh == 1) {
                        $('#hh').attr('onclick', 'qiandao(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 签到 </span>')
                    } else if (arr.hh == 2) {
                        $('#hh').attr('onclick', '');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 已签到 </span>')
                    } else if (arr.hh == 3) {
                        $('#hh').attr('onclick', 'guanzhu(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 关注 </span>')
                    } else if (arr.hh == 4) {
                        $('#hh').attr('onclick', 'noguanzhu(' + arr.user_id + ')');
                        $('#heheda').html('<i class="lmlblog-icon"></i> 取消关注 </span>')
                    }
                })
            })
        }
    </script>
</head>

<body>
<div class="lmlblog-member-main">
    <div class="lmlblog-member-bg">
        <div class="lmlblog-member-content">
            <div class="lmlblog-member-header">
                <div class="lmlblog-member-avatar other">
                    <a id="info_a"><img id="info_img" src="{{ head_info.userimg }}"
                                        onclick="ajax_header(2)"
                                        class="avatar" alt="加载失败"></a>
                    <i id="info_img_name" class="lmlblog-verify lmlblog-verify-a"
                       title="{{ head_info.userid.user_name }}"></i>
                </div>
                <div class="lmlblog-member-username">
                    <h1 id="info_user_name">{{ head_info.userid.user_name }}</h1>
                    <span class="lmlblog-mark lmlblog-lv" id="info_grade"
                          title="经验：3815">Lv.{{ head_info.userid.user_one_level }}</span>
                    <span class="lmlblog-mark lmlblog-vip"
                          id="info_sgrade">VIP {{ head_info.userid.user_member_level }}</span>
                </div>
                <div class="lmlblog-member-desc" id="info_sign">{{ head_info.userid.user_sign }}</div>
                <div class="lmlblog-member-follow-info">
                    {% if hh == 1 %}
                        <a id="hh" target="_blank" rel="nofollow" onclick="qiandao({{ head_info.userid.id }})"> <span
                                class="follow no opacity" id="heheda"><i class="lmlblog-icon"></i> 签到 </span></a>
                    {% elif hh == 2 %}
                        <a id="hh" target="_blank" rel="nofollow" onclick=""><span
                                class="follow no opacity" id="heheda"><i class="lmlblog-icon"></i>已签到</span></a>
                    {% elif hh == 3 %}
                        <a id="hh" target="_blank" rel="nofollow" onclick="guanzhu({{ head_info.userid.id }})"><span
                                class="follow no opacity" id="heheda"><i class="lmlblog-icon"></i> 关注 </span></a>
                    {% elif hh == 4 %}
                        <a id="hh" target="_blank" rel="nofollow" onclick="noguanzhu({{ head_info.userid.id }})"><span
                                class="follow no opacity" id="heheda"><i class="lmlblog-icon"></i> 取消关注 </span></a>
                    {% endif %}

                    <span class="opacity"><i class="lmlblog-icon">&#xe612;</i> <a
                            href="{% url 'body:index' %}">我的首页</a></span>
                </div>
            </div>
            <!-- {#            <div class="lmlblog-member-header">#}
            {#                <div class="lmlblog-member-avatar other">#}
            {#                    <a href="#" id="info_a"><img id="info_img" src="{% static 'home/css/default_avatar.png' %}"#}
            {#                                                 onclick="ajax_header(1)" class="avatar" alt="加载失败"></a>#}
            {#                    <i id="info_img_name" class="lmlblog-verify lmlblog-verify-a" title="用户名"></i></div>#}
            {#                <div class="lmlblog-member-username">#}
            {#                    <h1 id="info_user_name">用户名</h1>#}
            {#                    <span class="lmlblog-mark lmlblog-lv" id="info_grade" title="经验值">等级</span>#}
            {#                    <span class="lmlblog-mark lmlblog-vip" id="info_sgrade">会员等级</span></div>#}
            {#                <div class="lmlblog-member-desc" id="info_sign">个性签名</div>#}
            {#                <div class="lmlblog-member-follow-info" id="pin">#}
            {#关注 签到 私聊 异步加载地址#}
            {#                </div>#} -->
        </div>

        {% block show %}

        {% endblock %}
    </div>
</div>
<!-- 底部 -->
<div style="clear:both"></div>
<div class="footer">
    <div class="footer_b_foot">
        <div class="footer_b_top">
        </div>
        <div class="footer_b_bottom">Design by 2017 画江湖杯莫停 司空琪个人主页 司空琪微博/空间/贴吧官博。内容源于网络搜集,仅学习、分享交流。</div>
    </div>
</div>
<!-- 返回顶部 -->
<a href="javascript:returnTop();" class="cd-top"></a>
{% block script_content %}
{% endblock %}
</body>
{% block script_content2 %}
{% endblock %}
</html>

templates/register.html
{% load static %}
<!Doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <title>注册</title>
  <script language="javascript" type="text/javascript">
  function display(){
      var div1 = document.getElementById("div1");
      if(div1.style.display=="none"){
          div1.style.display = "block";
          div2.style.display = "none";
      }else{
          div1.style.display = "none";
          div2.style.display = "block";
      }
  }

  function display1(){
      var div1 = document.getElementById("div1");
      if(div1.style.display!="none"){
          div1.style.display = "none";
          div2.style.display = "block";
      }else{
          div1.style.display = "block";
          div2.style.display = "none";
      }
  }
  </script>

    <link rel="stylesheet" href="{% static 'css/cityselect.css' %}">
<style type="text/css">
	.demo{width:220px;margin:50px auto;}
	.demo input{padding: 12px 18px;}
</style>


 </head>
 <body>
<form action="{% url 'logins:register' %}" method="post">
    {% csrf_token %}
<div id="div1">

    手机号：<input type="tel" name="tel" pattern="^(0|86|17951)?(13[0-9]|15[012356789]|17[0678]|18[0-9]|14[57])[0-9]{8}" minlength="11" maxlength="11" placeholder="请输入11位手机号码" >
    密码：<input type="password" name="pwd" pattern="[0-9|A-z]{6}" placeholder="请输入6位密码">
    <input type="button" value="下一页" onclick="display()" >



</div>
<div id="div2" style="display: none">
{#      user_sign  #}
    姓名：<input type="text" name="name" style="line-height: 28px" minlength="1" maxlength="4" placeholder="'请输入您的姓名">
    性别：<input type="radio" checked="" name="sex" value="男" style="line-height: 28px">男
         <input type="radio" checked="" name="sex" value="女" style="line-height: 28px">女
    生日：<input type="date" name="birth" style="line-height: 28px" minlength="1">
    所在地：<input type="text" class="cityinput" id="citySelect" placeholder="请输居住地" name="city">
    个性标签： <input type="text" name="sign" placeholder="请输入您个人的简短介绍">
    <input type="button" value="上一页" onclick="display1()">
    <input type="submit" value="提交">
</div>
 </form>

 <script type="text/javascript" src="{% static 'js/cityselect.js' %}"></script>
<script type="text/javascript">
	var test=new Vcity.CitySelector({input:'citySelect'});
</script>
 </body>
</html>

templates/retrieve_password.html
{% extends 'account_template.html' %}
{% load staticfiles %}

{% block static %}
    找回密码/Password
{% endblock %}

{% block body %}
    <div class="wid_con loginbox">
        <div class="password_con">
            <div class="text_box">
                <div>
                    <div><i><img src="images/icon01.png"></i><input type="text" placeholder="请输入您的WangID号码">
                        <span>*</span>
                    </div>
                    <div class="yzm">
                        <i><img src="images/icon03.png"></i><input type="text" placeholder="请输入验证码">
                        <label><img src="images/yzm.png"></label><span>*</span>
                    </div>
                    <a href="{% url 'logins:change' %}">
                        <button>提 交</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="password_txt">
            <div>
                <h1>温馨提示</h1>
                <p>提交找回密码后, 我们会将您的密码发送至您注册时所填写的邮箱，请您注意查看</p>
            </div>
            <h2>若想起密码，请点此<a href="{% url 'logins:login' %}">登录</a></h2>
        </div>
    </div>
{% endblock %}